# Categories for document classification
categories:
  - تقنية
  - علوم
  - أعمال
  - تعليم

# Document processing and storage settings
document_settings:
  allowed_extensions:
    - .txt
    - .md
    - .pdf
    - .docx
  max_file_size: 5242880
  storage_directory: documents
  encoding: utf-8

# Metadata field configurations
metadata_fields:
  required:
    - title
    - category
    - date
    - keywords
  optional:
    - source
    - author
    - version

# Search and retrieval configurations
search_settings:
  case_sensitive: false
  include_metadata: true
  max_results: 50

# Logging configurations
logging:
  level: DEBUG
  directory: logs
  file_format: "bot_%Y%m%d.log"
