# Categories for document classification
categories:
  - تقنية
  - علوم
  - أعمال
  - تعليم

# Document processing and storage settings
document_settings:
  allowed_extensions:
    - .txt
    - .md
    - .pdf
    - .docx
  max_file_size: 15728640  # 15MB in bytes
  storage_directory: documents
  encoding: utf-8
  chunk_size: 1000
  chunk_overlap: 200

# Vector store settings
vector_store:
  persist_directory: db
  collection_name: documents
  distance_metric: cosine

# Model settings
model_settings:
  model_name: gpt-3.5-turbo
  temperature: 0
  max_tokens: 2000
  streaming: true

# Metadata field configurations
metadata_fields:
  required:
    - title
    - category
    - date
    - keywords
  optional:
    - source
    - author
    - version

# Search and retrieval configurations
search_settings:
  case_sensitive: false
  include_metadata: true
  max_results: 50
  fetch_k: 100
  score_threshold: 0.5
  filter_duplicates: true

# Logging configurations
logging:
  level: DEBUG
  directory: logs
  file_format: "bot_%Y%m%d.log"
