categories:
- تقنية
- علوم
- أعمال
- تعليم
document_settings:
  allowed_extensions:
  - .txt
  - .md
  max_file_size: 5242880
metadata_fields:
  optional:
  - source
  - author
  - version
  required:
  - title
  - category
  - date
  - keywords
search_settings:
  case_sensitive: false
  include_metadata: true
  max_results: 50
